# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import time
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


ASSETS_PATH = "build/assets/frame0"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def initialize_window():
    window = Tk()

    window.geometry("1950x1080")
    window.configure(bg="#2C2C2C")

    canvas = Canvas(
        window,
        bg="#2C2C2C",
        height=1080,
        width=1800,
        bd=0,
        highlightthickness=0,
        relief="ridge",
    )

    canvas.place(x=0, y=0)

    return window, canvas


window, canvas = initialize_window()
window.resizable(False, False)


# turn on stop screen
def create_stop_screen():
    image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(190.0, 127.0, image=image_image_1)

    image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(974.0, 540.0, image=image_image_2)

    button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat",
    )
    button_1.place(x=832.0, y=922.0, width=256.0, height=91.0)

    button_image_hover_1 = PhotoImage(file=relative_to_assets("button_hover_1.png"))

    def button_1_hover(e):
        button_1.config(image=button_image_hover_1)

    def button_1_leave(e):
        button_1.config(image=button_image_1)

    button_1.bind("<Enter>", button_1_hover)
    button_1.bind("<Leave>", button_1_leave)

    # Return references to prevent garbage collection
    return image_image_1, image_image_2, button_image_1, button_image_hover_1, button_1

# turn on wait screen
def create_wait_screen():
    image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(190.0, 127.0, image=image_image_3)

    image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(974.0, 540.0, image=image_image_4)

    button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat",
    )
    button_3.place(x=832.0, y=922.0, width=256.0, height=91.0)

    button_image_hover_3 = PhotoImage(file=relative_to_assets("button_hover_3.png"))

    def button_3_hover(e):
        button_3.config(image=button_image_hover_3)

    def button_3_leave(e):
        button_3.config(image=button_image_3)

    button_3.bind("<Enter>", button_3_hover)
    button_3.bind("<Leave>", button_3_leave)

    # Return references to prevent garbage collection
    return image_image_3, image_image_4, button_image_3, button_image_hover_3, button_3

# turn on go screen
def create_go_screen():
    image_image_5 = PhotoImage(file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(190.0, 127.0, image=image_image_5)

    image_image_6 = PhotoImage(file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(974.0, 540.0, image=image_image_6)

    button_image_5 = PhotoImage(file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat",
    )
    button_5.place(x=832.0, y=922.0, width=256.0, height=91.0)

    button_image_hover_5 = PhotoImage(file=relative_to_assets("button_hover_5.png"))

    def button_5_hover(e):
        button_5.config(image=button_image_hover_5)

    def button_5_leave(e):
        button_5.config(image=button_image_5)

    button_5.bind("<Enter>", button_5_hover)
    button_5.bind("<Leave>", button_5_leave)

    # Return references to prevent garbage collection
    return image_image_5, image_image_6, button_image_5, button_image_hover_5, button_5


# Call the function
#stop_screen_elements = create_stop_screen()
#time.sleep(1000)
#wait_screen_elements = create_wait_screen()
#time.sleep(1000)
go_screen_elements = create_go_screen()

# end of stop screen


window.mainloop()
